#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Emergency Mode for CS50 Appliance' --class cs50 --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.10.7-200.fc19.i686.PAE-recovery-5c6237e2-64c6-4618-b852-b3b8f282e251' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  2fdfabd4-36cc-4a49-901e-9c13f0f6ec38
	else
	  search --no-floppy --fs-uuid --set=root 2fdfabd4-36cc-4a49-901e-9c13f0f6ec38
	fi
	linux	/vmlinuz-3.10.7-200.fc19.i686.PAE root=/dev/mapper/fedora-root ro emergency rd.lvm.lv=fedora/swap rd.md=0 rd.dm=0  rd.luks=0 vconsole.keymap=us rd.lvm.lv=fedora/root rhgb quiet
	initrd	/initramfs-3.10.7-200.fc19.i686.PAE.img
}
