<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.2 setup script
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['auth_http_realm'] = 'CS50 Appliance';
$cfg['Servers'][$i]['hide_db'] = 'information_schema|mysql|performance_schema';

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['AllowUserDropDatabase'] = true;
$cfg['SuggestDBName'] = false;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['AjaxEnable'] = false;
$cfg['VersionCheck'] = false;
$cfg['DisplayDatabasesList'] = 0;
$cfg['ShowPhpInfo'] = true;
$cfg['ShowAll'] = true;
$cfg['NavigationBarIconic'] = 'both';
$cfg['PmaNoRelation_DisableWarning'] = true;
?>
